# Generated by Django 5.2.13 on 2026-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service_price_auto_service_price_camioneta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_camion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
