# Generated by Django 5.2.13 on 2026-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_service_price_camion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'base_manager_name': 'objects', 'ordering': ['service_type', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
