# Generated by Django 5.2.14 on 2026-06-10 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# (key, nombre, orden, campo_capacidad_legacy, campo_visibilidad_legacy)
DEFAULT_SECTORS = (
    ("lavadero", "Lavadero", 0, "default_capacity_wash", "public_show_wash_services"),
    ("detailing", "Detailing", 1, "default_capacity_detailing", "public_show_detailing_services"),
)

# Traduccion del enum legacy Service.service_type -> Sector.key.
SERVICE_TYPE_TO_SECTOR_KEY = {
    "wash": "lavadero",
    "combo": "lavadero",
    "detailing": "detailing",
}


def seed_and_backfill_sectors(apps, schema_editor):
    BusinessAccount = apps.get_model("core", "BusinessAccount")
    BusinessProfile = apps.get_model("core", "BusinessProfile")
    Sector = apps.get_model("catalog", "Sector")
    Service = apps.get_model("catalog", "Service")

    fallback_capacity = getattr(settings, "DEFAULT_DAILY_CAPACITY", 8)

    for business in BusinessAccount.objects.all().iterator():
        profile = BusinessProfile.objects.filter(business=business).first()
        sectors = {}
        for key, name, order, capacity_field, visibility_field in DEFAULT_SECTORS:
            capacity = getattr(profile, capacity_field, fallback_capacity) if profile else fallback_capacity
            visible = getattr(profile, visibility_field, True) if profile else True
            sector, _ = Sector.objects.get_or_create(
                business=business,
                key=key,
                defaults={
                    "name": name,
                    "order": order,
                    "default_capacity": capacity if capacity is not None else fallback_capacity,
                    "public_visible": bool(visible),
                },
            )
            sectors[key] = sector

        for service_type, sector_key in SERVICE_TYPE_TO_SECTOR_KEY.items():
            Service.objects.filter(
                business=business,
                service_type=service_type,
                sector__isnull=True,
            ).update(sector=sectors[sector_key])

        # Cualquier servicio con tipo inesperado cae al sector Lavadero.
        Service.objects.filter(business=business, sector__isnull=True).update(sector=sectors["lavadero"])


def remove_sectors(apps, schema_editor):
    Sector = apps.get_model("catalog", "Sector")
    Service = apps.get_model("catalog", "Service")
    Service.objects.update(sector=None)
    Sector.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_service_options_service_deleted_at'),
        ('core', '0023_businessprofile_capacity_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('icon', models.CharField(blank=True, max_length=24)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('default_capacity', models.PositiveIntegerField(default=8)),
                ('public_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='core.businessaccount')),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.sector'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('business', 'key'), name='uniq_sector_key_per_business'),
        ),
        migrations.RunPython(seed_and_backfill_sectors, remove_sectors),
    ]
