# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.db import migrations, models

from core.migration_operations import AddIndexConcurrentlyIfPostgres


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY no puede correr dentro de una transaccion.
    atomic = False

    dependencies = [
        ('catalog', '0010_servicematerial'),
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
    ]

    operations = [
        AddIndexConcurrentlyIfPostgres(
            model_name='sector',
            index=models.Index(fields=['business', 'is_active'], name='sector_biz_active_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='service',
            index=models.Index(fields=['business', 'is_active'], name='service_biz_active_idx'),
        ),
    ]
