# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_sector_sector_biz_active_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'base_manager_name': 'objects', 'ordering': ['order', 'name'], 'verbose_name': 'sector', 'verbose_name_plural': 'sectores'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'base_manager_name': 'objects', 'ordering': ['sector__order', 'name'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AlterModelOptions(
            name='servicematerial',
            options={'ordering': ['id'], 'verbose_name': 'receta de material', 'verbose_name_plural': 'recetas de materiales'},
        ),
    ]
