# Generated by Django 5.2.13 on 2026-06-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto'), ('camioneta', 'Camioneta'), ('combi', 'Combi')], default='auto', max_length=20),
        ),
    ]
