# Generated by Django 5.2 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_publicrequest_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrequest',
            name='push_subscription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
