# Generated by Django 5.2.13 on 2026-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_publicrequest_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto'), ('camioneta', 'Camioneta'), ('combi', 'Combi'), ('camion', 'Camion')], default='auto', max_length=20),
        ),
    ]
