# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_publicrequest_vehicle_type'),
        ('notifications', '0003_publicrequest_push_subscription'),
    ]

    operations = [
    ]
