# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationoutbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicrequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'solicitud pública', 'verbose_name_plural': 'solicitudes públicas'},
        ),
        migrations.AlterModelOptions(
            name='publicrequestitem',
            options={'ordering': ['id'], 'verbose_name': 'ítem de solicitud', 'verbose_name_plural': 'ítems de solicitud'},
        ),
    ]
