# Generated by Django 5.2.14 on 2026-06-05 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_businessprofile_public_service_type_filters'),
        ('debts', '0004_debt_business'),
        ('inventory', '0007_inventory_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=160)),
                ('creditor', models.CharField(blank=True, max_length=140)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_category', models.CharField(default='Servicios', max_length=80)),
                ('expense_subcategory', models.CharField(blank=True, default='Otros', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('interval_unit', models.CharField(choices=[('days', 'Dias'), ('weeks', 'Semanas'), ('months', 'Meses')], default='months', max_length=10)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_offset_days', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_cycles', models.PositiveIntegerField(blank=True, null=True)),
                ('cycles_generated', models.PositiveIntegerField(default=0)),
                ('last_generated_for', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_settle', models.BooleanField(default=False)),
                ('auto_settle_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_debts', to='core.businessaccount')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_debts', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-is_active', 'concept', '-id'],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_debts', to='debts.recurringdebt'),
        ),
    ]
