# Generated by Django 5.2.13 on 2026-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_recurring_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'base_manager_name': 'objects', 'ordering': ['-origin_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='debtpayment',
            options={'base_manager_name': 'objects', 'ordering': ['-paid_at', '-id']},
        ),
        migrations.AddField(
            model_name='debt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
