# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.db import migrations, models

from core.migration_operations import AddIndexConcurrentlyIfPostgres


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY no puede correr dentro de una transaccion.
    atomic = False

    dependencies = [
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
        ('debts', '0006_alter_debt_options_alter_debtpayment_options_and_more'),
        ('finance', '0007_alter_cashmovement_options_alter_payment_options_and_more'),
        ('inventory', '0011_merge_0010_leaf_migrations'),
    ]

    operations = [
        AddIndexConcurrentlyIfPostgres(
            model_name='debt',
            index=models.Index(fields=['business', '-origin_date'], name='debt_biz_origin_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['business', 'due_date'], name='debt_biz_due_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['business', '-paid_at'], name='debtpay_biz_paid_idx'),
        ),
    ]
