# Generated by Django 5.2.14 on 2026-06-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_legacy_capacity_visibility_fields'),
        ('debts', '0006_alter_debt_options_alter_debtpayment_options_and_more'),
        ('finance', '0007_alter_cashmovement_options_alter_payment_options_and_more'),
        ('inventory', '0011_merge_0010_leaf_migrations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0)), name='debt_principal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='debtpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='debtpayment_amount_positive'),
        ),
    ]
