# Generated by Django 5.2.13 on 2026-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_alter_debt_options_alter_debtpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringdebt',
            options={'base_manager_name': 'objects', 'ordering': ['-is_active', 'concept', '-id']},
        ),
        migrations.AddField(
            model_name='recurringdebt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
