# Generated by Django 5.2.14 on 2026-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
        ('debts', '0007_debt_debt_biz_origin_idx_debt_debt_biz_due_idx_and_more'),
        ('finance', '0008_cashmovement_cashmovement_amount_non_negative_and_more'),
        ('inventory', '0012_materialpurchase_matpur_biz_purchased_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0)), name='debt_principal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='debtpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='debtpayment_amount_positive'),
        ),
    ]
