# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0008_debt_debt_principal_amount_positive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'base_manager_name': 'objects', 'ordering': ['-origin_date', '-id'], 'verbose_name': 'deuda', 'verbose_name_plural': 'deudas'},
        ),
        migrations.AlterModelOptions(
            name='debtpayment',
            options={'base_manager_name': 'objects', 'ordering': ['-paid_at', '-id'], 'verbose_name': 'pago de deuda', 'verbose_name_plural': 'pagos de deuda'},
        ),
    ]
