# Generated by Django 5.2.14 on 2026-06-10 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_businessprofile_capacity_defaults'),
        ('finance', '0007_alter_cashmovement_options_alter_payment_options_and_more'),
        ('inventory', '0009_alter_material_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('concept', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_category', models.CharField(default='Servicios', max_length=80)),
                ('expense_subcategory', models.CharField(blank=True, default='Otros', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('interval_unit', models.CharField(choices=[('weeks', 'Semanas'), ('months', 'Meses')], default='months', max_length=10)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_offset_days', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_cycles', models.PositiveIntegerField(blank=True, null=True)),
                ('cycles_generated', models.PositiveIntegerField(default=0)),
                ('last_generated_for', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_pay', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='transfer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expenses', to='core.businessaccount')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expenses', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-is_active', 'concept', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FixedExpenseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_category', models.CharField(default='Servicios', max_length=80)),
                ('expense_subcategory', models.CharField(blank=True, default='Otros', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada')], default='pending', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='transfer', max_length=20)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expense_occurrences', to='core.businessaccount')),
                ('cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expense_occurrence', to='finance.cashmovement')),
                ('fixed_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='fixed_expenses.fixedexpense')),
            ],
            options={
                'ordering': ['-period_date', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('fixed_expense', 'period_date'), name='unique_active_fixed_expense_period')],
            },
        ),
    ]
