# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.db import migrations, models

from core.migration_operations import AddIndexConcurrentlyIfPostgres


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY no puede correr dentro de una transaccion.
    atomic = False

    dependencies = [
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
        ('finance', '0007_alter_cashmovement_options_alter_payment_options_and_more'),
        ('fixed_expenses', '0001_initial'),
        ('inventory', '0011_merge_0010_leaf_migrations'),
    ]

    operations = [
        AddIndexConcurrentlyIfPostgres(
            model_name='fixedexpense',
            index=models.Index(fields=['business', 'is_active'], name='fixexp_biz_active_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='fixedexpenseoccurrence',
            index=models.Index(fields=['business', 'status', 'period_date'], name='fixocc_biz_status_dt_idx'),
        ),
    ]
