# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_expenses', '0002_fixedexpense_fixexp_biz_active_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedexpense',
            options={'base_manager_name': 'objects', 'ordering': ['-is_active', 'concept', '-id'], 'verbose_name': 'gasto fijo', 'verbose_name_plural': 'gastos fijos'},
        ),
        migrations.AlterModelOptions(
            name='fixedexpenseoccurrence',
            options={'base_manager_name': 'objects', 'ordering': ['-period_date', '-id'], 'verbose_name': 'ocurrencia de gasto fijo', 'verbose_name_plural': 'ocurrencias de gasto fijo'},
        ),
    ]
