# Generated by Django 5.2.13 on 2026-05-09 13:20

import django.core.validators
from datetime import timedelta
from decimal import Decimal
from django.db import migrations, models


def base36(value):
    alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    number = int(value)
    if number == 0:
        return "0"
    result = ""
    while number:
        number, index = divmod(number, 36)
        result = alphabet[index] + result
    return result


def backfill_quote_commercial_fields(apps, schema_editor):
    Quote = apps.get_model("quotes", "Quote")
    BusinessProfile = apps.get_model("core", "BusinessProfile")
    profile = BusinessProfile.objects.order_by("id").first()
    business_name = profile.name if profile else "ShineApp"
    for quote in Quote.objects.select_related("customer", "vehicle").iterator():
        quote.public_code = quote.public_code or f"{quote.quote_date:%d%m%y}-{base36(quote.id).zfill(6)[-6:]}"
        quote.valid_until = quote.valid_until or quote.quote_date + timedelta(days=7)
        quote.business_name = quote.business_name or business_name
        if quote.customer_id:
            quote.customer_snapshot_name = quote.customer_snapshot_name or quote.customer.name
            quote.customer_snapshot_phone = quote.customer_snapshot_phone or quote.customer.phone
            quote.customer_snapshot_email = quote.customer_snapshot_email or quote.customer.email
        if quote.vehicle_id:
            quote.vehicle_snapshot_label = quote.vehicle_snapshot_label or str(quote.vehicle)
        quote.taxable_amount = quote.subtotal
        quote.save(
            update_fields=[
                "public_code",
                "valid_until",
                "business_name",
                "customer_snapshot_name",
                "customer_snapshot_phone",
                "customer_snapshot_email",
                "vehicle_snapshot_label",
                "taxable_amount",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businessprofile_address_and_more'),
        ('customers', '0005_customer_billing_address_customer_tax_id'),
        ('quotes', '0002_quote_reservation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='business_address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='quote',
            name='business_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='business_contact_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='quote',
            name='business_cuit',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='quote',
            name='business_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='quote',
            name='business_vat_condition_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_snapshot_billing_address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_snapshot_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_snapshot_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_snapshot_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_snapshot_tax_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='public_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='quote',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='vehicle_snapshot_label',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.RunPython(backfill_quote_commercial_fields, migrations.RunPython.noop),
    ]
