# Generated by Django 5.2.13 on 2026-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'base_manager_name': 'objects', 'ordering': ['-quote_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='quote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
