# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.db import migrations, models

from core.migration_operations import AddIndexConcurrentlyIfPostgres


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY no puede correr dentro de una transaccion.
    atomic = False

    dependencies = [
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
        ('customers', '0010_search_indexes'),
        ('quotes', '0005_alter_quote_options_alter_quoteitem_options_and_more'),
        ('scheduling', '0013_make_reservation_sector_required'),
    ]

    operations = [
        AddIndexConcurrentlyIfPostgres(
            model_name='quote',
            index=models.Index(fields=['business', '-quote_date'], name='quote_biz_qdate_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='quote',
            index=models.Index(fields=['business', 'status'], name='quote_biz_status_idx'),
        ),
    ]
