# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_quote_biz_qdate_idx_quote_quote_biz_status_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'base_manager_name': 'objects', 'ordering': ['-quote_date', '-id'], 'verbose_name': 'cotización', 'verbose_name_plural': 'cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'base_manager_name': 'objects', 'ordering': ['id'], 'verbose_name': 'ítem de cotización', 'verbose_name_plural': 'ítems de cotización'},
        ),
    ]
