# Generated by Django 5.2.15 on 2026-07-08 19:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_service_estimated_material_cost'),
        ('customers', '0011_alter_customer_options_alter_vehicle_options'),
        ('quotes', '0007_alter_quote_options_alter_quoteitem_options'),
        ('scheduling', '0015_reservationmaterialoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuoteVehicleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reservation_day', models.DateField(blank=True, null=True)),
                ('reservation_exit_day', models.DateField(blank=True, null=True)),
                ('reservation_start_time', models.TimeField(blank=True, null=True)),
                ('reservation_exit_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('vehicle_snapshot_label', models.CharField(blank=True, max_length=220)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_lines', to='quotes.quote')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_vehicle_line', to='scheduling.reservation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_vehicle_lines', to='customers.vehicle')),
            ],
            options={
                'verbose_name': 'linea de vehiculo de cotizacion',
                'verbose_name_plural': 'lineas de vehiculo de cotizacion',
                'ordering': ['order', 'id'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='QuoteVehicleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(max_length=180)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.service')),
                ('vehicle_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quotevehicleline')),
            ],
            options={
                'verbose_name': 'item de linea de vehiculo',
                'verbose_name_plural': 'items de linea de vehiculo',
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
