# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.conf import settings
from django.db import migrations, models

from core.migration_operations import AddIndexConcurrentlyIfPostgres


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY no puede correr dentro de una transaccion.
    atomic = False

    dependencies = [
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
        ('customers', '0010_search_indexes'),
        ('tasks', '0002_task_customer_vehicle_recurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrentlyIfPostgres(
            model_name='task',
            index=models.Index(fields=['business', 'status'], name='task_biz_status_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='task',
            index=models.Index(fields=['business', 'assignee'], name='task_biz_assignee_idx'),
        ),
    ]
