# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_biz_status_idx_task_task_biz_assignee_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'base_manager_name': 'objects', 'ordering': ['-id'], 'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
    ]
