# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
