# Generated by Django 5.2.13 on 2026-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_vehicle_license_plate_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
