# Generated by Django 5.2.13 on 2026-06-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_vehicle_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto'), ('camioneta', 'Camioneta'), ('combi', 'Combi')], default='auto', max_length=20),
        ),
    ]
