# Generated by Django 5.2.13 on 2026-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_businessprofile_reservation_status_flags'),
        ('customers', '0008_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'base_manager_name': 'objects', 'ordering': ['license_plate']},
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_vehicle_license_plate_per_business_when_present',
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('license_plate', ''), _negated=True), ('deleted_at__isnull', True)), fields=('business', 'license_plate'), name='unique_vehicle_license_plate_per_business_when_present'),
        ),
    ]
