# Generated by Django 5.2.14 on 2026-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_legacy_capacity_visibility_fields'),
        ('customers', '0009_alter_customer_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'name'], name='customer_biz_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['business', 'license_plate'], name='vehicle_biz_lp_idx'),
        ),
    ]
