# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_search_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'base_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'base_manager_name': 'objects', 'ordering': ['license_plate'], 'verbose_name': 'vehículo', 'verbose_name_plural': 'vehículos'},
        ),
    ]
