# Generated by Django 5.2.13 on 2026-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payment_cashmovement_business_date_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'base_manager_name': 'objects', 'ordering': ['-occurred_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'objects', 'ordering': ['-paid_at', '-id']},
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
