# Generated by Django 5.2.14 on 2026-06-12 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_legacy_capacity_visibility_fields'),
        ('finance', '0007_alter_cashmovement_options_alter_payment_options_and_more'),
        ('inventory', '0011_merge_0010_leaf_migrations'),
        ('workorders', '0007_make_workorder_sector_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='cashmovement_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
