# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_cashmovement_cashmovement_amount_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashclosure',
            options={'ordering': ['-day'], 'verbose_name': 'cierre de caja', 'verbose_name_plural': 'cierres de caja'},
        ),
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'base_manager_name': 'objects', 'ordering': ['-occurred_at', '-id'], 'verbose_name': 'movimiento de caja', 'verbose_name_plural': 'movimientos de caja'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'objects', 'ordering': ['-paid_at', '-id'], 'verbose_name': 'pago', 'verbose_name_plural': 'pagos'},
        ),
    ]
