# Generated by Codex on 2026-05-07

import decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_add_tool_inventory"),
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialOpenUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opened_at", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierta"), ("finished", "Finalizada")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("finished_at", models.DateField(blank=True, null=True)),
                (
                    "stock_quantity_to_decrement",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("1.00"),
                        max_digits=12,
                    ),
                ),
                ("estimated_unit_cost_at_open", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="open_units",
                        to="inventory.material",
                    ),
                ),
                (
                    "opened_by_work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_material_units",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="open_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumptions",
                to="inventory.materialopenunit",
            ),
        ),
    ]
