# Generated by Django 5.2.13 on 2026-05-07 15:59

from django.db import migrations, models


def move_available_tools_to_in_use(apps, schema_editor):
    Tool = apps.get_model('inventory', 'Tool')
    Tool.objects.filter(status='available').update(status='in_use')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_material_open_units'),
    ]

    operations = [
        migrations.RunPython(move_available_tools_to_in_use, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('in_use', 'En uso'), ('maintenance', 'Mantenimiento'), ('retired', 'Retirada')], default='in_use', max_length=20),
        ),
    ]
