# Generated by Django 5.2.13 on 2026-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_businessprofile_reservation_status_flags'),
        ('inventory', '0008_materialconsumption_business_consumed_at_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='material',
            name='unique_material_sku_per_business_when_present',
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sku', ''), _negated=True), ('deleted_at__isnull', True)), fields=('business', 'sku'), name='unique_material_sku_per_business_when_present'),
        ),
    ]
