# Generated by Django 5.2.14 on 2026-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_legacy_capacity_visibility_fields'),
        ('inventory', '0009_alter_material_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['business', 'name'], name='material_biz_name_idx'),
        ),
    ]
