# Generated by Django 5.2.14 on 2026-06-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_legacy_capacity_visibility_fields'),
        ('inventory', '0011_merge_0010_leaf_migrations'),
        ('workorders', '0007_make_workorder_sector_required'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='material_stock_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0)), name='material_minimum_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_unit_cost__gte', 0)), name='material_estimated_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='materialconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='materialconsumption_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='materialpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='materialpurchase_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='materialpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='materialpurchase_total_cost_non_negative'),
        ),
    ]
