# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.db import migrations, models

from core.migration_operations import AddIndexConcurrentlyIfPostgres


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY no puede correr dentro de una transaccion.
    atomic = False

    dependencies = [
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
        ('customers', '0010_search_indexes'),
        ('inventory', '0011_merge_0010_leaf_migrations'),
        ('scheduling', '0013_make_reservation_sector_required'),
        ('workorders', '0007_make_workorder_sector_required'),
    ]

    operations = [
        AddIndexConcurrentlyIfPostgres(
            model_name='materialpurchase',
            index=models.Index(fields=['business', '-purchased_at'], name='matpur_biz_purchased_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='stockmovement',
            index=models.Index(fields=['business', '-occurred_on'], name='stockmv_biz_occurred_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='stockmovement',
            index=models.Index(fields=['business', 'movement_type', 'occurred_on'], name='stockmv_biz_type_occ_idx'),
        ),
    ]
