# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_material_material_stock_quantity_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'base_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'material', 'verbose_name_plural': 'materiales'},
        ),
        migrations.AlterModelOptions(
            name='materialconsumption',
            options={'ordering': ['-consumed_at', '-id'], 'verbose_name': 'consumo de material', 'verbose_name_plural': 'consumos de material'},
        ),
        migrations.AlterModelOptions(
            name='materialopenunit',
            options={'ordering': ['-opened_at', '-id'], 'verbose_name': 'unidad abierta', 'verbose_name_plural': 'unidades abiertas'},
        ),
        migrations.AlterModelOptions(
            name='materialpurchase',
            options={'ordering': ['-purchased_at', '-id'], 'verbose_name': 'compra de material', 'verbose_name_plural': 'compras de material'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-occurred_on', '-id'], 'verbose_name': 'movimiento de stock', 'verbose_name_plural': 'movimientos de stock'},
        ),
        migrations.AlterModelOptions(
            name='stockmovementline',
            options={'ordering': ['id'], 'verbose_name': 'línea de movimiento', 'verbose_name_plural': 'líneas de movimiento'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'base_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'base_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'herramienta', 'verbose_name_plural': 'herramientas'},
        ),
    ]
