# Generated by Django 5.2.14 on 2026-06-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_sector_options_alter_service_options_and_more'),
        ('inventory', '0014_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialopenunit',
            name='is_historical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialopenunit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_open_units', to='catalog.service'),
        ),
    ]
