# Generated by Django 5.2.14 on 2026-06-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_material_sector'),
        ('inventory', '0015_open_unit_service_historical'),
    ]

    operations = [
    ]
