# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="exit_day",
            field=models.DateField(blank=True, null=True),
        ),
    ]
