# Generated by Codex on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_reservation_exit_day"),
        ("scheduling", "0002_reservationitem"),
    ]

    operations = []
