# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_merge_0002_reservation_exit_day_0002_reservationitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="exit_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
