# Generated by Django 5.2.13 on 2026-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_reservation_business_day_status_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'base_manager_name': 'objects', 'ordering': ['day', 'start_time', 'id']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
