# Generated by Django 5.2.13 on 2026-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_reservation_options_reservation_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationitem',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
