# Generated by Django 5.2.14 on 2026-06-10 12:59

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_reservation_sector(apps, schema_editor):
    Reservation = apps.get_model("scheduling", "Reservation")
    Service = apps.get_model("catalog", "Service")
    Reservation.objects.filter(sector__isnull=True).update(
        sector_id=Subquery(
            Service.objects.filter(pk=OuterRef("service_id")).values("sector_id")[:1]
        )
    )


def clear_reservation_sector(apps, schema_editor):
    Reservation = apps.get_model("scheduling", "Reservation")
    Reservation.objects.update(sector=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sector_service_sector_and_more'),
        ('scheduling', '0011_delete_dailycapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.sector'),
        ),
        migrations.RunPython(backfill_reservation_sector, clear_reservation_sector),
    ]
