# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_make_reservation_sector_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'base_manager_name': 'objects', 'ordering': ['day', 'start_time', 'id'], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AlterModelOptions(
            name='reservationitem',
            options={'base_manager_name': 'objects', 'ordering': ['id'], 'verbose_name': 'ítem de reserva', 'verbose_name_plural': 'ítems de reserva'},
        ),
    ]
