# Generated by Django 5.2.13 on 2026-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorder_business_created_at_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='workorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
