# Generated by Django 5.2.14 on 2026-06-10 12:59

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_workorder_sector(apps, schema_editor):
    WorkOrder = apps.get_model("workorders", "WorkOrder")
    Reservation = apps.get_model("scheduling", "Reservation")
    WorkOrder.objects.filter(sector__isnull=True).update(
        sector_id=Subquery(
            Reservation.objects.filter(pk=OuterRef("reservation_id")).values("sector_id")[:1]
        )
    )


def clear_workorder_sector(apps, schema_editor):
    WorkOrder = apps.get_model("workorders", "WorkOrder")
    WorkOrder.objects.update(sector=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sector_service_sector_and_more'),
        ('scheduling', '0012_reservation_sector'),
        ('workorders', '0005_alter_workorder_options_workorder_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='catalog.sector'),
        ),
        migrations.RunPython(backfill_workorder_sector, clear_workorder_sector),
    ]
