# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_make_workorder_sector_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at'], 'verbose_name': 'orden de trabajo', 'verbose_name_plural': 'órdenes de trabajo'},
        ),
    ]
