# Generated by Django 5.2.13 on 2026-05-08 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ShineApp', max_length=160)),
                ('logo', models.FileField(blank=True, upload_to='business-profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])])),
                ('cuit', models.CharField(blank=True, max_length=11)),
                ('vat_condition', models.CharField(blank=True, choices=[('responsable_inscripto', 'Responsable inscripto'), ('monotributo', 'Monotributo'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor final')], max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil del negocio',
                'verbose_name_plural': 'perfil del negocio',
            },
        ),
    ]
