# Generated by Django 5.2.13 on 2026-05-09 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_business_profile_operational_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Prueba'), ('premium', 'Premium')], default='trial', max_length=16),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to='user-profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])])),
                ('phone_country_code', models.CharField(choices=[('+54', 'Argentina (+54)'), ('+598', 'Uruguay (+598)'), ('+56', 'Chile (+56)'), ('+55', 'Brasil (+55)'), ('+595', 'Paraguay (+595)'), ('+591', 'Bolivia (+591)'), ('+51', 'Peru (+51)'), ('+57', 'Colombia (+57)'), ('+52', 'Mexico (+52)')], default='+54', max_length=8)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
    ]
