# Generated by Django 5.2.13 on 2026-05-09 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_businessprofile_subscription_type_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="logo",
            field=models.FileField(
                blank=True,
                upload_to="business-profile/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "webp", "svg", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.FileField(
                blank=True,
                upload_to="user-profiles/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "webp", "svg", "pdf"]
                    )
                ],
            ),
        ),
    ]
