# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.conf import settings
from django.db import migrations, models

from core.migration_operations import AddIndexConcurrentlyIfPostgres


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY no puede correr dentro de una transaccion.
    atomic = False

    dependencies = [
        ('core', '0024_remove_legacy_capacity_visibility_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrentlyIfPostgres(
            model_name='auditlog',
            index=models.Index(fields=['business', '-created_at'], name='audit_biz_created_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='auditlog',
            index=models.Index(fields=['business', 'module', '-created_at'], name='audit_biz_module_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='auditlog',
            index=models.Index(fields=['business', 'action', '-created_at'], name='audit_biz_action_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='auditlog',
            index=models.Index(fields=['business', 'entity_type', 'entity_id'], name='audit_biz_entity_idx'),
        ),
    ]
