# Generated by Django 5.2.14 on 2026-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auditlog_audit_biz_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'registro de auditoría', 'verbose_name_plural': 'registros de auditoría'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'token de restablecimiento', 'verbose_name_plural': 'tokens de restablecimiento'},
        ),
    ]
