# Generated by Django 5.2.15 on 2026-07-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_businesshours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialFollowUp',
            fields=[
            ],
            options={
                'verbose_name': 'seguimiento de trial',
                'verbose_name_plural': 'seguimiento de trials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.businessprofile',),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='trial_followup_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='trial_followup_status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('demo_scheduled', 'Demo agendada'), ('converted', 'Convertido'), ('lost', 'Perdido')], db_index=True, default='new', max_length=24),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='trial_last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='trial_next_followup_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
