# Generated by Django 5.2.4 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_businessprofile_onboarding_dismissed_step_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lavadero", "Lavadero"),
                    ("detailing", "Detailing"),
                    ("lubricentro", "Lubricentro"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
