# Generated by Django 5.2.4 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_businessprofile_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="use_cash_closures",
            field=models.BooleanField(default=False),
        ),
    ]
